//#include<iostream>
//using namespace std;
//void function3()
//{
//	throw runtime_error("Runtime ");
//}
//void function1()
//{
//	try
//	{
//		cout << "Hello\n";
//	}
//	catch (runtime_error& ex)
//	{
//		cout << "abc xyz\n";
//	}
//	function3();
//	cout << "bdjaj\n";
//}
//void Test1()
//{
//	try
//	{
//		cout << "This is a line\n";
//		function1();
//	}
//	catch (out_of_range& ex)
//	{
//		cout << "abc xyz\n";
//	}
//}
//void main()
//{
//	try
//	{
//		Test1();
//	}
//	catch (runtime_error& ex1)
//	{
//		cout << "Caught at 123\n";
//		throw ex1;
//	}
//	catch (exception& ex2)
//	{
//		cout << "456\n";
//	}
//
//}
